Added additional test cases for the TimeStringParser.
StateSmith/StateSmith pull request #169
Opened 2023-04-14 15:03 UTC by RadtkeTomasz

Following the convention of the file, I added some tests that fit more supported time units criteria.

Added an important CultureInfo.InvariantCulture argument to the Double parsing method (TimeStringParser line 72) which avoids the "String not in correct format" exception when testing from another country (the exception was thrown while performing original tests before any changes, in testing the "ExpectOk" "4.25 min" string).

2023-04-14 19:48 UTC, adamfk commented
Thanks! Will check out after work tonight :)

2023-04-14 23:49 UTC, adamfk commented on src/StateSmithTest/Common/TimeStringParserTests.cs
> +        ExpectBadInput("-15 blissful sniffs");
Loved these! Made me laugh out loud 😆

2023-04-15 00:11 UTC, adamfk requested changes
Looks good! Just need to remove the .wsuo file I think, and remove the TODOs that you completed.

Thanks!

2023-04-15 00:11 UTC, adamfk commented on .vs/StateSmith/v17/.wsuo
is the .wsuo file intended to be committed?

2023-04-15 00:11 UTC, adamfk commented on src/StateSmith/Common/TimeStringParser.cs
> +        number = double.Parse(match.Groups["number"].Value, CultureInfo.InvariantCulture);
good call. I wasn't aware of this until last week when a user reported a bug. #159

This kind of info is very much appreciated.

2023-04-15 00:11 UTC, adamfk commented on src/StateSmithTest/Common/TimeStringParserTests.cs
>          // TODO add all variations https://github.com/StateSmith/StateSmith/issues/131
I think we can remove the `// TODO` lines now. The code coverage looks pretty good to me.

2023-04-15 06:25 UTC, RadtkeTomasz commented on .vs/StateSmith/v17/.wsuo
It was not - sorry. I wasn't aware of this file's creation - it was generated automatically. The .suo or .wsuo files are VS files to store local data about user solution options. I cannot even locate it through VS Solution Explorer to mark it as ignored, so I edited the gitignore file to include .wsuo. I hope this resolves the problem.

2023-04-15 06:26 UTC, RadtkeTomasz commented on src/StateSmith/Common/TimeStringParser.cs
> +        number = double.Parse(match.Groups["number"].Value, CultureInfo.InvariantCulture);
I am glad I could contribute !

2023-04-15 06:39 UTC, RadtkeTomasz commented on src/StateSmithTest/Common/TimeStringParserTests.cs
>          // TODO add all variations https://github.com/StateSmith/StateSmith/issues/131
Please check if it's okay now - I am not 100% sure that the wsuo file is now ignored or not. (I ignored the whole local .vs folder through the projects gitignore file). Thanks

2023-04-15 13:57 UTC, adamfk approved these changes

2023-04-15 13:59 UTC, merged